name: Episode Validation Comment

on:
  workflow_run:
    workflows: ["Validate Episode Files"]
    types:
      - completed

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    permissions:
      pull-requests: write
    steps:
      - name: Download PR number artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: pr-validation-data
          path: pr

      - name: Get PR number
        id: pr
        run: |
          number=$(cat pr/NR)
          echo "::set-output name=number::$number"

      - name: Create comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: episode-validation
          number: ${{ steps.pr.outputs.number }}
          path: pr/validation-report.md
