name: Upload Episode to Spotify

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - fix/fix-youtube-to-spotify
    # paths:
    #   - "episodes/**.md"

jobs:
  upload-episode:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: 📦 Setup Node + PNPM + install deps
      #   uses: ./.github/actions/setup-node-pnpm-install

      # - name: Get missed episode + generate youtube id file missed-episode.json
      #   id: missed-episode
      #   run: |
      #     node ./.github/scripts/get-missed-episode.js

      # - name: Check if missed episode exists
      #   id: check-file
      #   run: |
      #     if [ -f "missed-episode.json" ]; then
      #       echo "exists=true" >> $GITHUB_OUTPUT
      #     else
      #       echo "exists=false" >> $GITHUB_OUTPUT
      #     fi

      # - name: Setup yt-dlp YouTube cookies
      #   uses: AnimMouse/setup-yt-dlp/cookies@v3
      #   with:
      #     cookies: ${{ secrets.YOUTUBE_COOKIES }}
      #     enable: false

      - name: Upload Episode from YouTube To Spotify
        uses: yjose/youtube-to-spotify@feat-cookies
        env:
          SPOTIFY_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          SPOTIFY_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
          EPISODE_PATH: /github/workspace
          COOKIES_FILE: ${{ secrets.YOUTUBE_COOKIES }}
          SAVE_AS_DRAFT: true
          # LOAD_THUMBNAIL: true
          # URL_IN_DESCRIPTION: true
          EPISODE_FILE: missed-episode.json
